controller_list:
  - name: fake_robot1_controller
    type: $(arg fake_execution_type)
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses per group
  - group: robot1
    pose: random